# fly.toml app configuration file generated for gsn-relay-mumbai on 2024-02-01T15:41:54-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gsn-relay-base-mainnet'
primary_region = 'sea'

[env]
config = '/app/config/gsn-relay-config.json'
RELAYER_URL = 'https://gsn-relay-base.rly.network/'                        # **
RELAYER_HUB_ADDRESS = '0x54623092d2dB00D706e0Ad4ADaCc024F9cB9E915'
RELAYER_MANAGER_STAKE_TOKEN_ADDRESS = '0x4200000000000000000000000000000000000006'
RELAYER_OWNER_ADDRESS = '0xA3888cee7A5a616ca330ABb0FB9d962B5C105d7A'
RELAYER_PAYMASTER_ADDRESS = '0x01B83B33F0DD8be68627a9BE68E9e7E3c209a6b1'
RELAYER_PAYMASTER_MIN_BALANCE = '100000000000000000'
RELAYER_GAS_PRICE_FACTOR = 1
RELAYER_WORKER_MIN_BALANCE = '100000000000000000'
RELAYER_WORKER_TARGET_BALANCE = '200000000000000000'
RELAYER_MANAGER_MIN_BALANCE = '100000000000000000'
RELAYER_MANAGER_TARGET_BALANCE = '200000000000000000'
RELAYER_RUN_PAYMASTER_REPUTATIONS = false
RELAYER_MAX_MAX_FEE_PER_GAS = '1500000000000'

[build]

[http_service]
internal_port = 8090
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 2
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024

[[http_service.checks]]
grace_period = '5s'
interval = '3s'
method = 'GET'
timeout = '1s'
path = '/health'

[deploy]
strategy = 'bluegreen'
